# TimeTuner Configuration
# Version: 1.1.0

# =====================================================
# GLOBAL TIME SPEED SETTINGS
# =====================================================
# These settings apply to all worlds unless overridden
# in the world-specific section below.
# 
# Values explained:
# - 1.0 = Vanilla Minecraft speed (normal)
# - 0.5 = Half speed (time passes at 50% of normal rate)
# - 2.0 = Double speed (time passes twice as fast)
# =====================================================
global-speeds:
  day-speed: 0.5    # Global day speed multiplier
  night-speed: 1.0  # Global night speed multiplier

# =====================================================
# SLEEP SETTINGS
# =====================================================
sleep:
  allow-skip: true           # Enable night skipping via sleep
  percentage: 0.50           # Percentage of players required to skip (0.50 = 50%)
  use-required-players: false # Use fixed player count instead of percentage
  required-players: 3        # Number of players required when use-required-players is true

# =====================================================
# WORLD-SPECIFIC SETTINGS
# =====================================================
# Override global settings for specific worlds.
# Each world can have its own:
#   - day-speed: Custom day speed (overrides global setting)
#   - night-speed: Custom night speed (overrides global setting)
#   - enabled: true/false (whether time management is active)
#   - allow-bed-explosions: true/false (whether bed explosions are allowed)
#   - allow-thunderstorm-sleep: true/false (whether thunderstorms can be skipped by sleep)
#
# Note: Each world can be individually paused/resumed using commands:
#   /timetuner pause <world>
#   /timetuner resume <world>
# =====================================================
worlds:
  world:
    day-speed: 0.30
    night-speed: 0.5
    enabled: true
    allow-bed-explosions: false
    allow-thunderstorm-sleep: true
  
  world_nether:
    day-speed: 1.0
    night-speed: 1.0
    enabled: false
    allow-bed-explosions: true
    
  
  world_the_end:
    day-speed: 1.0
    night-speed: 1.0
    enabled: false
    allow-bed-explosions: true
    
# =====================================================
# SAFETY FEATURES
# =====================================================
safety:
  overflow-protection: true  # Prevents time overflow issues (recommended)
  
# =====================================================
# ADVANCED SETTINGS
# =====================================================
advanced:
  tick-frequency: 1       # How often to update time (in ticks, 1-20)
  debug-mode: false       # Enables verbose logging
  auto-pause-empty: false # Pause time when no players are in a world