name: TimeTuner
version: 1.2.1
main: me.summykai.timetuner.TimeTuner
api-version: 1.21
authors: [summykai]
description: A sophisticated time management plugin for Minecraft Paper servers offering precise control over day/night cycles with production-grade reliability and intuitive commands.
website: https://github.com/summykai/timetuner

commands:
  timetuner:
    description: Master command for TimeTuner plugin
    aliases: [tt]
    usage: /<command> [reload|pause|resume|speed|status|reset|help]
    permission: timetuner.admin

permissions:
  timetuner.use:
    description: Access to basic commands
    default: false
    children:
      timetuner.status: true
      timetuner.help: true

  timetuner.admin:
    description: Full configuration access
    default: op
    children:
      timetuner.reload: true
      timetuner.pause: true
      timetuner.resume: true
      timetuner.speed: true
      timetuner.reset: true
      timetuner.use: true

  timetuner.reload:
    description: Allows reloading TimeTuner configuration
    default: op

  timetuner.pause:
    description: Allows pausing/resuming time progression
    default: op
    
  timetuner.resume:
    description: Allows resuming time progression
    default: op

  timetuner.speed:
    description: Allows changing global time speeds
    default: op

  timetuner.status:
    description: Allows viewing plugin status
    default: true

  timetuner.help:
    description: Allows viewing help information
    default: true

  timetuner.reset:
    description: Allows resetting world times
    default: op